//> using publish.name "scalacon2022-demo"
//> using publish.repository "central-s01"
//> using publish.license "Apache-2.0"
//> using publish.url "https://github.com/alexarchambault/scalacon2022-demo"
//> using publish.versionControl "github:alexarchambault/scalacon2022-demo"
//> using publish.developer "Alex Archambault||https://github.com/alexarchambault"
//> using publish.computeVersion "git:tag"
//> using publish.ci.computeVersion "git:tag"
//> using publish.ci.repository "central-s01"
//> using publish.ci.user "env:PUBLISH_USER"
//> using publish.ci.password "env:PUBLISH_PASSWORD"
//> using publish.ci.secretKey "env:PUBLISH_SECRET_KEY"
//> using publish.ci.secretKeyPassword "env:PUBLISH_SECRET_KEY_PASSWORD"
